FROM node:15 

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y wget

ENV DATABASE_URL=postgresql://postgres:mysecretpassword@some-postgres:5432/postgres

ENV PORT=3333

ENV DOCKERIZE_VERSION v0.6.1

CMD ["npm","run", "dev"]